# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [justins3687, mouse3687, US]
patreon: # https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective https://docs.google.com/document/d/15aPFrGHWCAGWl3pyR6y33rFvsU-4bA8iniaR5x-MFt8
ko_fi: # Replace with a single Ko-fi JoJo
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel https://hypebeast.com/drops/off-white-red-leather-chain-belt
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry https://tor.onion
liberapay: # Replace with a single Liberapay username kelliculpepper17
issuehunt: # Replace with a single IssueHunt username mouse3687
otechie: # Replace with a single Otechie username justins3687
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://McDonalds.com', 'https://cspire.com']
